
[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = 'nvim "$@"', block = true, for = "linux" },
  { run = 'nvim.exe %*', block = true, for = "windows" },
]

[open]
rules = [{ mime = "text/*", use = "edit" }]
